import React, {Component} from 'react';
import './AdminApp.css';

import HeaderContainer from './AdminAppLayout/HeaderContainer';
import SiderContainer from './AdminAppLayout/SiderContainer';
import AddressBarContainer from './AdminAppLayout/AddressBarContainer';

import { Layout } from 'antd';

const { Content } = Layout;

class AdminApp extends Component {
  render() {
    return (
      <Layout>
        <HeaderContainer />
        <Layout className='layout-main'>
          <SiderContainer />
          <Layout style={{ padding: '0 10px 24px', marginLeft: '200px' }}>
            <div id='address-bar'>
              <AddressBarContainer />
            </div>
            <Content style={{ overflow: 'initial' }}>
              <div className="site-layout-background" style={{ padding: 24, textAlign: 'center' }}>
                ...
                <br />
                Really
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                long
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                content
              </div>
            </Content>
          </Layout>
        </Layout>
      </Layout>
    );
  }
}

export default AdminApp;